image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &


build_script:
  - ./gradlew test --info -Dselenide.headless=true